"""empty message

Revision ID: a0abd97f95f1
Revises: 8e9a111c1613
Create Date: 2022-06-03 13:58:24.801505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0abd97f95f1'
down_revision = '8e9a111c1613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'upcoming')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('upcoming', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
